# Generated by Django 2.2.3 on 2019-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('ip', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('mac', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
    ]
